Squeezelite /etc/init.d/ scripts

diff --git a/board/nanopi-neo/S95squeezelite b/board/nanopi-neo/S95squeezelite
--- a/board/nanopi-neo/S95squeezelite
+++ b/board/nanopi-neo/S95squeezelite
@@ -1,3 +1,40 @@
 #!/bin/sh
 
-squeezelite -z -n SqueezeliteNanoPiNeo -o hw:0,0 -a 200::: -s 192.168.0.23
+NAME=squeezelite
+DAEMON=/usr/bin/$NAME
+PIDFILE=/var/run/$NAME.pid
+# Read: squeezelite -?
+DAEMON_ARGS="-z -n SqueezeliteNanoPiNEO -o hw:0,0 -s 192.168.0.23"
+
+# Sanity checks
+test -f $DAEMON || exit 0
+
+start() {
+        printf "Starting $NAME: "
+        start-stop-daemon --start --quiet --background --exec $DAEMON \
+                -- $DAEMON_ARGS \
+                && echo "OK" || echo "FAIL"
+}
+
+stop() {
+        printf "Stopping $NAME: "
+        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
+                && echo "OK" || echo "FAIL"
+}
+
+case "$1" in
+        start)
+                start
+                ;;
+        stop)
+                stop
+                ;;
+        restart)
+                stop
+                sleep 1
+                start
+                ;;
+        *)
+                echo "Usage: $0 {start|stop|restart}"
+                exit 1
+esac
